
# En production, externaliser le fichier : 
# java -jar mon-app.jar --spring.config.location=file:/chemin/externe/application.properties

spring.application.name=demo-dsfr-rest

# ----------------------------------------------------------------------------------------------
# API DE SANTE
# ----------------------------------------------------------------------------------------------
# /auditevents Liste les evenements lies aux audits de securite (connexion/deconnexion, etc..).
# /beans Liste les beans disponibles.
# /conditions Rapport des conditions pour l'autoconfiguration.
# /configprops Liste les beans de type @ConfigurationProperties.
# /env Renvoie les proprietes de l'environnement.
# /health Etat de sante de l'application.
# /heapdump Cree un dump à partir de la JVM utilisee par l'application.
# /info Renvoie les informations generales pour l'application.
# /flyway Details sur les migrations de bases de donnees Flyway.
# /liquibase se comporte comme /flyway mais pour Liquibase.
# /logfile Renvoie les journaux d'application ordinaires.
# /loggers Interroge le niveau de journalisation de notre application.
# /metrics Renvoie les métriques de l'application.
# /prometheus Renvoie des métriques, mais formatées pour fonctionner avec un serveur Prometheus.
# /scheduledtasks Détails sur chaque tâche planifiée dans l'application.
# /sessions Repertorie les sessions HTTP.
# /shutdown effectue un arret progressif de l'application.
# /threaddump vide les informations de thread de la JVM sous-jacente.

# Activation des points de terminaison pour l'api de sante, par defaut, seuls '/health' et '/info' sont actifs.
management.endpoints.web.exposure.include=health,info
# Securite si demande d'activation de l'ensemble des points de terminaison.
management.endpoints.web.exposure.exclude=mappings,heapdump

# Definition du port et de la racine des points de terminaison pour l'actuator.
# (a changer aussi au niveau du filtre de securite si besoin de modifications). 
management.endpoints.web.base-path=/actuator
management.server.port=8080

# Configuration du point de terminaison '/health', valeurs possibles <never|always|when_authorized>
# Pattern: management.endpoint.{endpoint-name}.{property}={value}
management.endpoint.health.show-details=never
management.health.defaults.enabled=false

# Activation du point de terminaison '/health' personnalise pour l'application demo-dsfr-rest.
# Si non actif, c'est le parametrage du '/health' par defaut qui est utilise. Si actif, 
# avec des options de détail, ne pas oublier de positionner correctement le parametre 
# 'management.endpoint.health.show-details' afin de visualiser aussi le detail.
management.health.demo-dsfr-rest_health.enabled=false

# Configuration du point  de terminaison /info, definir ici les informations necessaires.
management.info.env.enabled=true
app.cusomInfo=Une information de type custom...
info.app.cusomInfo=${app.cusomInfo}
info.app.java-version=${java.version}
info.app.java-vendor=${java.vendor}
info.app.excluded-actuator-enpoints=${management.endpoints.web.exposure.exclude}

# ----------------------------------------------------------------------------------------------
# SWAGGER UI
# ----------------------------------------------------------------------------------------------
# Documentation JSON ex: http://localhost:8080/v1/api-docs
springdoc.api-docs.path=/api-docs
# Documentation Swagger (ihm) ex: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui
# Definition de l'ordre d'affichage des operations (endpoints) <alpha|method>
springdoc.swagger-ui.operations-sorter=method
# Definition de l'ordre d'affichage des tags <alpha|fonction de tri JS personnalisee>
springdoc.swagger-ui.tags-sorter=alpha
# A définir si utilisation de la sécurité oauth2
springdoc.swagger-ui.oauth.client-id=pacman-dsfr-demo
# A définir si utilisation de la sécurité oauth2
springdoc.swagger-ui.oauth.use-pkce=true

# ----------------------------------------------------------------------------------------------
# LISTE DES URIS NON SECURISEES
# ----------------------------------------------------------------------------------------------
# Ne pas oublier de reporter les modifications issues des rubriques precedentes 
security.whitelist.paths=/swagger-ui/**,/api-docs/**,/actuator/**

# ----------------------------------------------------------------------------------------------
# SERVEUR AUTHENTIFICATION (SSO)
# ----------------------------------------------------------------------------------------------
security.jwt.issuer-uri=http://localhost:8085/realms/pacman-demo-realm

# ----------------------------------------------------------------------------------------------
# HTTP SERVER
# ----------------------------------------------------------------------------------------------
# Le port par defaut.
server.port=8081
# Chemin de contexte
server.servlet.context-path=/
# Encodage
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
# Un exemple de cle symetrique (pour le developpement uniquement).
security.jwt.secret=

# ----------------------------------------------------------------------------------------------
# LOGGING
# ----------------------------------------------------------------------------------------------
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG
# Format du log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
# Fichier de log
logging.file.name=logs/demo-dsfr-rest.log
logging.file.max-size=10MB
logging.file.total-size-cap=100MB

# ----------------------------------------------------------------------------------------------
# SPRING PROFILES
# ----------------------------------------------------------------------------------------------
spring.profiles.active=dev

# ----------------------------------------------------------------------------------------------
# SPRING CACHE 
# ----------------------------------------------------------------------------------------------
# Valeurs possibles <none|simple|caffeine|ehcache|hazelcast|infinispan|jcache|redis>
spring.cache.type=simple

# ----------------------------------------------------------------------------------------------
# CIRCUIT BREAKER
# ----------------------------------------------------------------------------------------------
# Enregistre un Health Indicator Spring Boot Actuator pour ce circuit breaker.
resilience4j.circuitbreaker.instances.externalServiceCircuitBreaker.registerHealthIndicator=true
# Seuil de déclenchement du circuit breaker : si 50% des appels échouent, le circuit bloque les appels.
resilience4j.circuitbreaker.instances.externalServiceCircuitBreaker.failureRateThreshold=50
# Une fois ouvert (OPEN), le circuit reste bloqué pendant 10 secondes.
resilience4j.circuitbreaker.instances.externalServiceCircuitBreaker.waitDurationInOpenState=10000ms
# En mode HALF_OPEN, seul un petit nombre d'appels test sont autorisés (ici 3).
resilience4j.circuitbreaker.instances.externalServiceCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
# Les 10 derniers appels sont analysés pour calculer le taux d'échec
resilience4j.circuitbreaker.instances.externalServiceCircuitBreaker.slidingWindowSize=10

# ----------------------------------------------------------------------------------------------
# STORAGE S3 (MINIO)
# ----------------------------------------------------------------------------------------------
# URL du serveur de stockage (par défaut : localhost:9000).
s3.url=http://localhost:9000
# Identifiant de connexion.
# s3.access-key=minioadmin (placé dans coffre-fort Vault)
# Mot de passe pour la connexion.
# s3.secret-key=minioadmin (placé dans coffre-fort Vault)
# Conteneur logique (comme un dossier racine).
s3.bucket=documents

# ----------------------------------------------------------------------------------------------
# COFFRE FORT (VAULT)
# ----------------------------------------------------------------------------------------------
# Active Vault comme source de configuration (si disponible)
spring.config.import=optional:vault://
# Activation ou désactivation du coffre fort.
spring.cloud.vault.enabled=true
# L'application échoue au démarrage si Vault est inaccessible.
spring.cloud.vault.fail-fast=false	
# URL de Vault (par défaut : http://localhost:8200).
spring.cloud.vault.uri=http://localhost:8200
# Méthode d'authentification <token|approle|userpass|etc...>
spring.cloud.vault.authentication=token
# Le token d'accès Vault (à ne pas utiliser en production (dev ou demo uniquement) !)
spring.cloud.vault.token=${PACMAN_DEMO_VAULT_TOKEN}
# Backend utilisé (kv v2 par défaut)
spring.cloud.vault.kv.enabled=true
# Nom du backend utilisé dans Vault (par défaut souvent secret).
spring.cloud.vault.kv.backend=secret
# Nom utilisé pour accéder au chemin dans Vault (ex. secret/data/myapp).
spring.cloud.vault.kv.application-name=demo-dsfr-rest

# ----------------------------------------------------------------------------------------------
# DATASOURCES
# ----------------------------------------------------------------------------------------------

# Note : il n'est pas utile de specifier le nom de classe du pilote, puisque Spring Boot 
# peut le deduire pour la plupart des bases de donnees a partir de l'URL de connexion.
# Si présence de schéma, il est aussi écrit au niveau de la chaine de connexion (mode create).

## pool de connexion par defaut
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

# En production placer a 'none'. valeurs possibles : <create | create-drop | update | validate | none>  
spring.jpa.hibernate.ddl-auto=create-drop  

# Fortement conseille de placer a 'false' (LazyInitializationException).
spring.jpa.open-in-view=false

# Active la poulation automatique de la base avec des données faker.
spring.populate.faker.enabled=true

# Strategie de nommage
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy

# Maintient la connexion active en cas d'inaction prolongee (necessaire en production).
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

# Debug des requetes sql pour le developpement (couper en production).
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# H2 DB (paramètres placés dans le coffre-fort vault)
# spring.datasource.url=jdbc:h2:file:C:/h2/test;DB_CLOSE_DELAY=-1;
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

## PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/<votre base de donnees>;DB_CLOSE_DELAY=-1;
#spring.datasource.username=<nom utilisateur>
#spring.datasource.password=<mot de passe utilisateur>
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




